steps:
- name: microsoft/dotnet:2.2-sdk
  args: ['dotnet', 'build']
- name: microsoft/dotnet:2.2-sdk
  args: ['dotnet', 'test', '--no-build']
- name: microsoft/dotnet:2.2-sdk
  entrypoint: 'bash'
  args: ['-c', 'cd source/Dgraph-dotnet.tests.e2e && dotnet run --no-build --no-restore']
  secretEnv: ['DGDNE2E_GraphSchemaIOConnection__ApiKeyId', 'DGDNE2E_GraphSchemaIOConnection__ApiKeySecret']
timeout: 240s

secrets:
- kmsKeyName: projects/dgraph-dotnet/locations/global/keyRings/graphschema-keys/cryptoKeys/gsio-key
  secretEnv:
    DGDNE2E_GraphSchemaIOConnection__ApiKeyId: CiQAslfEuB0Ma25c/SAmJekEjjUlN56RieppC34ts+hrifnxazISTQAe22TiBq4o7wGOUUUoKvXZFz+u2EIAuxP7KhJFXgyBXCnMx0sok9tvK16NCUPShHsozjO3Fhd0Asr3IziTqxkyXITF62tdz34FBE/v
    DGDNE2E_GraphSchemaIOConnection__ApiKeySecret: CiQAslfEuOeMJXZkZXUXQivFvEK8MsYKWMeikjYaVjRShuhpg/gSVQAe22TiZko28upONJbmin5bu/7TzxtBBiXq9fUSBw2ocQNnK+1hTsNA+5zp3hg8fUTkoGmoaa5LQhU7j0ERmr26Ih/gXUzStnyHqY1dKKnzOJT1lXM=
