steps:
- name: gcr.io/cloud-builders/git
  args: ['fetch', '--unshallow']
- name: gcr.io/graphschema/dotnet_gitversion
  args: ['bash', '-c', 'dotnet-gitversion /showvariable FullSemVer | sed "s/+/-/g" > GITVERSION']
- name: microsoft/dotnet:2.2-sdk
  args: ['bash', '-c', 'dotnet build -c Release -p:Version=$(cat GITVERSION)']
- name: microsoft/dotnet:2.2-sdk
  args: ['bash', '-c', 'dotnet test -c Release -p:Version=$(cat GITVERSION) --no-build --no-restore']
- name: microsoft/dotnet:2.2-sdk
  entrypoint: 'bash'
  args: ['-c', 'cd source/Dgraph-dotnet.tests.e2e && dotnet run --no-build --no-restore']
  secretEnv: ['DGDNE2E_GraphSchemaIOConnection__ApiKeyId', 'DGDNE2E_GraphSchemaIOConnection__ApiKeySecret']
- name: microsoft/dotnet:2.2-sdk
  args: ['bash', '-c', 'dotnet pack source/Dgraph-dotnet/Dgraph-dotnet.csproj -c Release -p:Version=$(cat GITVERSION) --no-restore --no-build --output ../../artifacts --include-symbols -p:SymbolPackageFormat=snupkg']
- name: microsoft/dotnet:2.2-sdk
  entrypoint: 'bash'
  args: ['-c', 'dotnet nuget push artifacts/Dgraph-dotnet.$(cat GITVERSION).nupkg -k $$NUGET_KEY -s https://api.nuget.org/v3/index.json']
  secretEnv: ['NUGET_KEY']
timeout: 240s

secrets:
- kmsKeyName: projects/dgraph-dotnet/locations/global/keyRings/graphschema-keys/cryptoKeys/nuget-key
  secretEnv:
    NUGET_KEY: CiQApAQ/k3VULPs5hj2kRL6gXQyb94OIHDV2hHOmRlaf2cWS4VwSWAC+fJfRoNsPlocnmRiyzppho5iqovEVUlVZi3ZZ0mlItxHUJpXpOtWKuTAgFENzLapF3PZtEKAqj0Je6ex49NNYrOWHcP0fD/Yc+loULySEQukLHZ0ujDY=
- kmsKeyName: projects/dgraph-dotnet/locations/global/keyRings/graphschema-keys/cryptoKeys/gsio-key
  secretEnv:
    DGDNE2E_GraphSchemaIOConnection__ApiKeyId: CiQAslfEuB0Ma25c/SAmJekEjjUlN56RieppC34ts+hrifnxazISTQAe22TiBq4o7wGOUUUoKvXZFz+u2EIAuxP7KhJFXgyBXCnMx0sok9tvK16NCUPShHsozjO3Fhd0Asr3IziTqxkyXITF62tdz34FBE/v
    DGDNE2E_GraphSchemaIOConnection__ApiKeySecret: CiQAslfEuOeMJXZkZXUXQivFvEK8MsYKWMeikjYaVjRShuhpg/gSVQAe22TiZko28upONJbmin5bu/7TzxtBBiXq9fUSBw2ocQNnK+1hTsNA+5zp3hg8fUTkoGmoaa5LQhU7j0ERmr26Ih/gXUzStnyHqY1dKKnzOJT1lXM=
